---
name: self-test

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        id: go
        with:
          go-version-file: "go.mod"
          cache-dependency-path: |
            go.sum

      - name: build and test
        run: |
          make test
        env:
          TZ: "Europe/Moscow"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
